app:
  title: Backstage Backend Test
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
    externalAccess:
      - type: static
        options:
          token: ${DCR_APPROVER_TOKEN}
          subject: dcr-approver-script
    providers:
      oidc:
        development:
          signIn:
            resolvers:
              - resolver: emailMatchingUserEntityProfileEmail
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  environment: development
  session:
    secret: your-session-secret

  providers:
    guest:
      userEntityRef: user:default/guest
      dangerouslyAllowOutsideDevelopment: false
    oidc:
      development:
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local
    local:
      publishDirectory: /home/tpetkos/dev-techdocs

notifications:
  processors:
    email:
      transportConfig:
        transport: 'stream'
      sender: 'Backstage <no-reply@localhost>'

catalog:
  providers:
    backstageOpenapi:
      plugins:
        - '@backstage/plugin-catalog-backend-module-openapi'

integrations:
  github:
    - host: github.com

scorecards:
  enabled: false